### ISSUE TITLE
Window border gone on Firefox 55

### ISSUE THREAD

**Issue by ianamk** [downthemall/downthemall-legacy#245]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll 3.0.8
Firefox 55.0 stable x64 on Windows 7 x64 English
### Expected Behavior
the window border to be shown so the DTA window be manipulated ie moved or closed

### Actual Behavior
window border to be shown

### Steps To Reproduce
just start DTA manager

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*
```
01:21:36::878
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:583
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:19
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:271
	unload/<() @ chrome://dta-modules/content/glue.jsm:351
--> chrome://dta/content/preferences/prefs.js:583:0
01:21:42::569
DownThemAll! (info) - Close request
	shutdown() @ chrome://dta/content/dta/manager/manager.js:1238
	close() @ chrome://dta/content/dta/manager/manager.js:1232
	onclose() @ chrome://dta/content/dta/manager/manager.js:1201
	init/<() @ chrome://dta/content/dta/manager/manager.js:222
--> chrome://dta/content/dta/manager/manager.js:1238:0
01:21:42::574
DownThemAll! (info) - Going to close all
	shutdown() @ chrome://dta/content/dta/manager/manager.js:1260
	close() @ chrome://dta/content/dta/manager/manager.js:1232
	onclose() @ chrome://dta/content/dta/manager/manager.js:1201
	init/<() @ chrome://dta/content/dta/manager/manager.js:222
--> chrome://dta/content/dta/manager/manager.js:1260:0
01:21:42::577
DownThemAll! (info) - Still running: 0 Finishing: 0
	shutdown() @ chrome://dta/content/dta/manager/manager.js:1284
	close() @ chrome://dta/content/dta/manager/manager.js:1232
	onclose() @ chrome://dta/content/dta/manager/manager.js:1201
	init/<() @ chrome://dta/content/dta/manager/manager.js:222
--> chrome://dta/content/dta/manager/manager.js:1284:0
01:21:42::603
```
a picture's worth a thousand words
https://i.imgur.com/F4jtzzQ.png

I've tested some other addons that use their own window (clav's cards still works) and downthemall is the only one showing this issue

**Comment by Mundo54** [comment]
same thing here and it persists in the Firefox 55.0.1 64-bit update today, Win7 Home Premium 64-bit

**Comment by pu-p** [comment]
Same problem. Here is my log:
[dta.txt](https://github.com/downthemall/downthemall/files/1219766/dta.txt)

**Comment by Rootzpower** [comment]
+1

**Comment by ianamk** [comment]
just tested it under Linux and this seams to be a windows only issue (not sure about Mac)
https://imgur.com/a/i6CRQ
I know DTA development is dead but can we please get a fix so we can use it under windows until we find a better browser 
I tried the nightly build from https://code.downthemall.net/nightly/
the bug is present there too :(

**Comment by ianamk** [comment]
accidentally hit close and comment instead of only comment

**Comment by Mundo54** [comment]
It still works on our Win10 MSI laptop with Firefox x64. I'll have to test it on our Win10 clone desktop system, currently powered down and not in use.

**Comment by ianamk** [comment]
strange enough it doesn't happen on my 32bit win10 device
https://imgur.com/a/GmHPz
I use sync and both devices have the same addons installed
it could be that my win7 profile is too old and something leftover is causing issues
I'll delete my old profile resync and try again, if it fixes things I'll report back

**Comment by ianamk** [comment]
nope I removed my profile
with only DTA! installed the issue is still there
https://imgur.com/a/jEsAB

**Comment by SylwesterZarebski** [comment]
Confirmed on W7 Pro & Ent x64, but not on W10 Pro x64.

**Comment by Vrchz** [comment]
And Win7 Ultimate x64

**Comment by hook321** [comment]
It probably still works in Pale Moon.

**Comment by southern-boy** [comment]
Same problem here.  No close or X option.  I have to use Alt F4 to close downloadthemall.  This is on Firefox 55 (32 bit) and Windows 7 (64) Home.

**Comment by Mundo54** [comment]
I use Win7 Classic and I can close it from a Right-Click option on the Taskbar
![downthemall_taskbar_close_window](https://user-images.githubusercontent.com/24293770/29483406-ae2edd28-8473-11e7-86d6-0fa914f670ed.png)

**Comment by southern-boy** [comment]
This problem of loosing the close menu happened with the last windows update or at least coincided with it.  I can also close the window by finding the app running in the task menu,  right click and select close or as it says use Alt F4 which is what I do.

**Comment by ianamk** [comment]
just tested the current trunk build from https://code.downthemall.net/nightly/downthemall-nightly-trunk.xpi
and the window border is back
a big tanks to the dta devs I'm closing this issue

**Comment by SylwesterZarebski** [comment]
Will there be released stable version for Firefox < 57? Outside of AMO of course.
