### ISSUE TITLE
downthemall.net expired 2017-08-29

### ISSUE THREAD

**Issue by davethegr8** [downthemall/downthemall-legacy#252]
Hi, sorry to file this here, but two days ago your domain expired. It looks like it's still in the redemption period.

![screen shot 2017-08-31 at 13 52 17](https://user-images.githubusercontent.com/55392/29944783-a16f0a2e-8e53-11e7-8869-da945b49f7ca.png)

**Comment by hook321** [comment]
@nmaier The extension still works great on Pale Moon, don't let someone snatch the domain. :/

**Comment by nmaier** [comment]
Yes, we know. Unfortunately Federico passed away some months ago, and he registered the domain, and now we're looking to how to get it back.

**Comment by nmaier** [comment]
We got access back, but it may take some time till the DNS caches worldwide update and see the change.
