### ISSUE TITLE
Add Support for firefox 59.0.1 

### ISSUE THREAD

**Issue by jega-ms** [downthemall/downthemall-legacy#286]
### Your DownThemAll! and Browser Version and Language and Operating System
Failed to install or update this plugin on "Firefox 59.0.1" . could you please add the support ?
<img width="645" alt="screen shot 2018-03-19 at 12 14 10 pm" src="https://user-images.githubusercontent.com/15880838/37581552-0eb9fcf2-2b6f-11e8-9a8d-774c2186f1ff.png">

**Comment by 5t0rmr1d3r** [comment]
Duplicate to #270
See also: https://www.downthemall.net

**Comment by GrooverMD** [comment]
Fantastic work my friend. As always people expect it now. Its hard to kick a goal when they move the goal posts (Mozilla). When it is ready cheers.
