### ISSUE TITLE
DTA is dead ! Don't support this scam, you'll loose your money, like me...

### ISSUE THREAD

**Issue by jarredou** [downthemall/downthemall-legacy#287]
I've supported the dev of DTA as the dev asked... and 4 months later, still nothing !
The main dev is playing dead since  december... with all our money in his pocket...
What a bad joke...

**Comment by xlimit91** [comment]
@jarredou the software is free, isnt it? So if you donate money to the dev, it does not mean he must work on the plugin. You do not know the reasons why it is taking so long. However, it is not scam because the software is 100% free.

**Comment by Colocho7** [comment]
Pues yo sigo usando Downthemall 3.1.1pre en Waterfox.. sin problemas :D 
https://code.downthemall.net/nightly/trunk/
https://www.waterfoxproject.org/en-US/

**Comment by Xmetalfanx** [comment]
I hope one of the devs/ops closes this thread soon ... even if i donated (this is like linux distros ... or say Youtube content creators) ... its sort of a "thank you" and "keep up the good work" ... we don't own the developer ... if anything I feel bad I do not have better skills to lend a hand to HELP the developer

**Comment by mariusfg** [comment]
jarredou how long have you been using DTA for free and for your benefit? Do you think it's fair to complain now ?

**Comment by iromeister** [comment]
DTA ain't dead, it's just asleep. ;-) And now that spring is coming forth, I'm sure it will wake up again soon.

**Comment by Logitech-byte** [comment]
Silence! DTA is not dead!

**Comment by ishaq** [comment]
@jarredou you have the code, go work on it and release a version.

**Comment by Xmetalfanx** [comment]
since this is still open (not sure if the dev(s?) will ever see this) I just want to take a second to THANK the dev(s?) for all the hard work they have done ... the fact that I love this add-on so much is one of the reason I hope it continues... .again Thank you

**Comment by Xan-Kun** [comment]
A BIG thank you to everybody involved in this project for the last (many) years! I totally understand why dta is dead. I totally not understand the issue title (WTF?!) and I just want to drop my x cents:

Leave those devs alone. What do you think what riches they got from your meager contributions? Sure, they all own multiple Teslas, many villas and the occasional tropic island. But hey, they deserve it! :-)

**Mozilla ruined Add-Ons.** Full stop. If anybody wants to complain, get some actual education and write to mozilla.

Again, thanks to Nils and everybody in the team for making my life much easier.
It was beautiful for the time it lasted *sadsigh*

**Comment by avatar21** [comment]
Damn ... please open source this and let the community do the job

**Comment by Zhuinden** [comment]
Tell Mozilla Foundation to stop killing the platform that plugins are written on, maybe they'd continue working

Apparently Basilisk browser is a Firefox fork that supports DTA.

**Comment by Xmetalfanx** [comment]
Waterfox does too (I never heard of Basilisk but am willing to look into it) ... I need DTA to work on a browser but I also admit I am typing this on Firefox 60 so .... no big deal ... heck I do web dev stuff so I have multiple browsers installed anyway

**Comment by jarredou** [comment]
The scam is the promise made by the dev months ago to develop a WebExt version of the plugin, promising the beta will arrive soon and asking money to support him in THIS hard work, but THIS work wasn't done and weeks became months. If the dev is not able to code the plugin alone, other people could help him, but it's not possible because he doesn't want to. 
This insulting thread was to provoke a reaction from the dev. Nothing happened. End of the story.

**Comment by Zhuinden** [comment]
WebExtensions might not cover this use case . Donations aren't a proof of purchase. You are donating so he has his time covered for an attempt, result is never guaranteed.

Use Basilisk.
