### ISSUE TITLE
DTA no longer works on Firefox 52.8.1 (64-bit)

### ISSUE THREAD

**Issue by drago454** [downthemall/downthemall-legacy#291]
### Your DownThemAll! and Browser Version and Language and Operating System
DTA 3.0.8, Firefox 52.8.1 (64-bit) English, Mac OS X 10.10.5

### Expected Behavior
Download files

### Actual Behavior
Add-on has been disabled with no way of turning it back on.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sensititive information which you have to remove prior to posting it!*

**Comment by iansebryk** [comment]
i know FF 52 has some issues with this, but i am using FF 56.0.2 (64bit) with updates disabled and it runs like a charm (DTA v3.0.8).  i hope DTA gets retooled for FFQ, but, despite all the notifications to the contrary, i have found no issues (security or performance) with FF 56 and i like that its stable on both my windoze and linux platforms.  if you're looking for a stable pre-Quantum solution, and aren't locked in to FF 52 for some reason, i recommend giving this configuration a go.  if you need links, just search for older versions and look for the last release before 57 (Quantum) and, as i presume you will also want, you'll need to manually install NoScript as well (v5.1.8.6) which you can find on the NoScript site.

**Comment by s4sutler100** [comment]
Where is the link for the previous FF?

**Comment by alavry** [comment]
@s4sutler100 
https://ftp.mozilla.org/pub/firefox/releases/

**Comment by Colocho7** [comment]
Pruebe con DTA 3.0.9alpha o DTA 3.1.1pre-alpha, son versiones nocturnas con actualizaciones diarias
https://code.downthemall.net/nightly/

**Comment by RobertOnGit** [comment]
I'm running Firefox 52.9.0 ESR (64-bit).
dTa 3.0.8 works fine on this version.
