### ISSUE TITLE
Personal legacy build compatible with current Nightly

### ISSUE THREAD

**Issue by sintapilgo** [downthemall/downthemall-legacy#292]
We know that all legacy addons still work in Nightly with `extensions.legacy.enabled = true`, `xpinstall.signatures.required = false` and some tweaks on code to keep up with moz changes, like `nsIPrefBranch2 -> nsIPrefBranch`, `getComplexValue(key, Ci.nsISupportsString).data -> getStringPref(key)`, inlining some XBL bindings and so on.

I was still using DTA! untill Fx 61, then 1448162 came disabling overlays. Like many other bugs since Fx 57 that affected DTA! (1374847, 1387805 1098412, 1392884, 1374247, 1414096, 1405491, 1414406, 1416368, 1419170, 1228841, 1379338, 792808, 1434163, 1435446, 1445551, 888600, 1448853), I tried to fix the code, but this one is complex. DTA! has `registerOverlay` that helps, I partially workarounded overlays so Manager and Prefs are working properly, but startup is failing and then the whole process of downloading. Seems to be related to glue.jsm, main.js or both.

Maybe you're doing this too, updating personal builds of DTA! to use on Nightly. If this is the case, could you please provide the current XPI? I know what to do, I think I just need to overcome 1448162. I think I could deal even with the imminent bootstrap.js removal (1449052) migrating to AutoConfig or Experiments.

Thank you.

**Comment by sintapilgo** [comment]
So I forgot about 1447719 and its `browser.startup.blankWindow`. Solved. Actually I had already been able to fix 1448162. DTA! is working fine here.

[screenshot](http://i.imgur.com/CNzXkcQ.png)

**Comment by hook321** [comment]
Can you upload the source code for this somewhere?
