### ISSUE TITLE
Cannot Install DTA on Firefox Quantum ver 61.0.1 (64-bit)

### ISSUE THREAD

**Issue by katrinkump** [downthemall/downthemall-legacy#293]
### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by crzsotona** [comment]
Why post issues about known incompatibility?
DTA still does **not** support Firefox Quantum
#269 #270 #275 #286

**Comment by Xmetalfanx** [comment]
I think alot of these issues that are basically saying the same thing, need to be closed and referenced to a single issue ... at least that is what other git repos have done with this sort of thing
