### ISSUE TITLE
DownThemAll! add-on missing from the Firefox Add-ons site

### ISSUE THREAD

**Issue by tigregalis** [downthemall/downthemall-legacy#298]
### Your DownThemAll! and Browser Version and Language and Operating System

Firefox 56.0.2
Latest DownThemAll
English Australian
Windows 10 64-Bit

### Expected Behavior

The url https://addons.mozilla.org/en-US/firefox/addon/downthemall/ should link to the add-on on the Firefox Add-on site. Searching for "downthemall" on the Firefox Add-on site should find the add-on page.

### Actual Behavior

Following the url https://addons.mozilla.org/en-US/firefox/addon/downthemall/ results in a Page not found error. Searching for "downthemall" on the Firefox Add-on site doesn't find it.

### Steps To Reproduce

Navigate to https://addons.mozilla.org/en-US/firefox/addon/downthemall/ or search for downthemall on the Firefox Add-ons site.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sensitive information which you have to remove prior to posting it!*

**Comment by hgdagon** [comment]
Mozilla had announced that they were going to remove old-format plugins. Not only DownThemAll! is missing.

**Comment by hook321** [comment]
@tigregalis 
It can be downloaded through SeaMonkey's/Thunderbird's addon site: https://addons.thunderbird.net/en-US/seamonkey/addon/downthemall/

It's probably compatible with atleast SeaMonkey and Waterfox still I'm guessing.

I would highly recommend switching to Waterfox or SeaMonkey instead of staying on Firefox 56 so that you still get security updates.

Project homepages: https://www.waterfoxproject.org/, https://seamonkey-project.org/

**Comment by Cyb3rG0D7** [comment]
Downtheamall 3.1.1-pre nightly
use Waterfox for plus security
https://www.waterfoxproject.org/en-US/
o Basilisk

**Comment by mjgiotto** [comment]
Mrs. hgdagon , hook54321 and Cyb3rG0D7, Thanks a lot, for this information about the program Downthenall, this is very useful.

**Comment by jaques-sam** [comment]
If the plugin has still an old format, the proper fix is to create a DownThemAll plugin with the correct format, right?

**Comment by nmaier** [comment]
The WebExtension is coming about: https://github.com/downthemall/downthemall

It is less capable than the "legacy" version
