### ISSUE TITLE
Not supported with new firefox update (Jun 1st).

### ISSUE THREAD

**Issue by psoto2** [downthemall/downthemall-legacy#299]
### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by d7415** [comment]
Yet another duplicate. Please look at existing issues before posting new ones.

(fwiw, this happened months ago. If you were still using DTA you were using an unsupported version of firefox)

**Comment by psoto2** [comment]
Yeah sorry.  So any alternatives?

**Comment by d7415** [comment]
> Yeah sorry. So any alternatives?

There are some options. None are a perfect replacement. I've been looking at [Download Star](https://github.com/marklieberman/downloadstar).
